name: Build ALl task
on: workflow_dispatch
jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo " Buid Stage"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo Test
        run: echo "Test stage"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: echo deplo
        run: echo "deploy stage"
