name: Test GHA
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo " This is build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo " This is test stage"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo " this is deploy stage"
