name: Test all phase
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deplpy
        run: echo "deploy"
