name: GHA input testing
on:
  workflow_dispatch:
    inputs:
      environment:
        description: choose env
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
          - test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: dispaly env:
        run: echo " you are runing job on ${{inputs.environment}}"
        
