name: testing on choice
on: 
  workflow_dispatch:
    inputs:
      environments:
        description: choose env
        required: true
        type: choice
        options: [dev,qa,prod]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: stage1
        run: echo "you are running job in ${{ inputs.environments }}"
