name: if codition in GHA
on: 
  pull_request:
    types: 
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "Buildling application"
