name: GHA input practice
on:
  workflow_dispatch:
    inputs:
      environments:
        description: 
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - test
          - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo env:
        run: echo "workflow is running on ${{ inputs.environments }}
