name: pull/push if condition
on:
  push:
    branches:
      - main
  pull_request:
    types: 
      - opened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-slim
    if: github.event_name == 'pull_request'
    steps:
      - name: Build
        run: echo "build stage triggered"
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - name: deploy
        run: echo "deploy stage tringred"
