name: Practice on variable
on:
  workflow_dispatch: 
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Variable practice
        run: echo "Hello ${{ vars.MY_NAME }} how are you"
  secret_practice:
    runs-on: ubuntu-slim
    steps:
      - name: secrete_practice
        run: echo "Docker secrets are ${{ secrets.KEY_NAME }}"
